### ISSUE TITLE
Time format not right?

### ISSUE THREAD

**Issue by bartkummel** [TheFes/cheapest-energy-hours#154]
Hi,

I'm following the documentation example to set up an automation to start my dishwasher at night during the cheapest hours. However, I keep getting issues where the sensor has the value "unkown" instead of a timestamp. I tried to debug using the templating section in developer tools. The output seems okay, but I noticed that the template's output has a `T` between the date and time, while other values (e.g. when calling `today_at()` in a template) have a space there. When I put a `as_datetime()` around the call to the template, I get a space too, instead of a `T`. When I apply this to the sensor, it does work as intended. Here's an example that I copy-pasted from my template scratchpad:
```
{%- set sensor = 'sensor.tibber_prices_2' -%}
{% from "cheapest_energy_hours.jinja" import cheapest_energy_hours %}

{{ cheapest_energy_hours(sensor=sensor, hours=2, start='22:00', end='08:00', look_ahead=true, include_tomorrow=true) }} 
#output: 2024-08-13T22:00:00+02:00

{{ as_datetime(cheapest_energy_hours(sensor=sensor, hours=2, start='22:00', end='08:00', look_ahead=true, include_tomorrow=true)) }} 
#output: 2024-08-13 22:00:00+02:00
```
I have a solution now, with the `as_timestamp`. However, either this should be added to the docs, or the template should be fixed so the output can be used directly.

**Comment by TheFes** [comment]
Both of these are using an isoformat datetime string (just like the output of the macro) 
![Screenshot_20240814-165606.png](https://github.com/user-attachments/assets/de728e40-3689-4704-b6ee-c6ed3bbd2890)

**Comment by bartkummel** [comment]
Thanks for your replay, @TheFes ! I was about to copy and paste a snippet from my `configuration.yaml`. But when I opened it to copy, I suddenly saw the error. I used the [example to set up a Tibber prices sensor](https://github.com/TheFes/cheapest-energy-hours/blob/main/documentation/1-source_sensor.md#tibber) That has some time formatting code in it, that uses a format without a `T` as separator. I don't understand exactly how, but apparently, that bubbles up to the outcome of the macro? Anyway, when I add that `T` in the pattern, the whole thing works. Here's the lines that I now changed, compared to the example:
```yaml
          start: "{{ (today_at() - timedelta(days=1)).strftime('%Y-%m-%dT%H:%M:%S') }}"
          end: "{{ (today_at() + timedelta(days=2)).strftime('%Y-%m-%dT%H:%M:%S') }}"
```
You might want to update the example. Thanks for asking the question that led me to solving the problem myself! 😉

**Comment by TheFes** [comment]
That's strange, because that's just the input for the ~~service call~~ action, I wouldn't think it affects the output of the response. 

I don't have a Tibber API key, so I can't test myself. But basically it can't affect the output of the macro, because the macro uses datetime objects when it's doing all the calculations. 

I can add the T, but I'm quite sure that your issue being solved by it is a coincidence. 

What could have happened is that the macro was returning an error before, which obviously isn't a datetime string. You could add something like `value_on_error=as_datetime(0).isoformat()` to make sure it always returns a valid output considering the device_class.
