### ISSUE TITLE
now

### ISSUE THREAD

**Issue by rhgiter** [TheFes/cheapest-energy-hours#69]
hi 

I have this 

{{ cheapest_energy_hours("sensor.energi_data_service", hours=3, time_format="%H:%M:%S", look_ahead=true, start="06:00", end="17:00", include_tomorrow=false) }}

and the output is for now 12:00:00 (cheapest)

but if I active my automation ex. 12:10 - my dishwasher will start tomorrow at 12:00

?

how do I get around this ?

**Comment by TheFes** [comment]
I have added a setting for that in the version I'm about to publish.
If you wait on that, and then add `look_ahead_minutes=0` it will always pick a start time in the future.

Alternative is to use the `is_now` mode, instead of the time.

What is best is depending on your preferences, and also on where you are using the output of the template.

**Comment by rhgiter** [comment]
Thanks ! :-)
